<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-01T01:18:48 CET" name="Default suite" finished-at="2022-11-01T01:18:57 CET" duration-ms="8551">
    <groups>
    </groups>
    <test started-at="2022-11-01T01:18:48 CET" name="Default test" finished-at="2022-11-01T01:18:57 CET" duration-ms="8551">
      <class name="ui.SeleniumExerciseTest">
        <test-method is-config="true" signature="gotoWebSite()[pri:0, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:48 CET" name="gotoWebSite" finished-at="2022-11-01T01:18:50 CET" duration-ms="1679" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gotoWebSite -->
        <test-method signature="firstTest()[pri:1, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:50 CET" name="firstTest" description="1st Test - Open the application and make sure a list of movie tiles is displayed." finished-at="2022-11-01T01:18:50 CET" duration-ms="185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method signature="secondTest()[pri:2, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:50 CET" name="secondTest" description="2nd Test - Open the movie The Shawshank Redemption and make sure the release date is correctly displayed." finished-at="2022-11-01T01:18:51 CET" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTest -->
        <test-method signature="thirdTest()[pri:3, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:51 CET" name="thirdTest" description="3rd Test - Retrieve the url of the image and open it in another tab then close the tab." finished-at="2022-11-01T01:18:51 CET" duration-ms="471" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method signature="fourthTest()[pri:4, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:51 CET" name="fourthTest" description="4th Test - Search for Star Trek and make sure that the movie Star Trek: First Contact is displayed in the search results and the movie The Shawshank Redemption is no longer visible." finished-at="2022-11-01T01:18:52 CET" duration-ms="1098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourthTest -->
        <test-method signature="fifthTest()[pri:5, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:52 CET" name="fifthTest" description="5th Test - Search for A New and verify that all the titles displayed contain the search phrase." finished-at="2022-11-01T01:18:54 CET" duration-ms="1196" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The title #10: The Gendarme in New York doesn't contain the search phrase expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The title #10: The Gendarme in New York doesn't contain the search phrase expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at ui.SeleniumExerciseTest.fifthTest(SeleniumExerciseTest.java:172)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fifthTest -->
        <test-method signature="sixthTest()[pri:6, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:54 CET" name="sixthTest" description="6th Test - Take any movie you like and make sure the Released on, popularity, vote average and vote count fields have the expected values." finished-at="2022-11-01T01:18:56 CET" duration-ms="2112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sixthTest -->
        <test-method signature="seventhTest()[pri:7, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:56 CET" name="seventhTest" description="7th Test - Search with empty field and check that some movies are there." finished-at="2022-11-01T01:18:57 CET" duration-ms="1066" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The movie The Shawshank Redemption is expected to be present expected [1] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The movie The Shawshank Redemption is expected to be present expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at ui.SeleniumExerciseTest.seventhTest(SeleniumExerciseTest.java:249)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seventhTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:ui.SeleniumExerciseTest@771a660]" started-at="2022-11-01T01:18:57 CET" name="closeBrowser" finished-at="2022-11-01T01:18:57 CET" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- ui.SeleniumExerciseTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
